export const SET_LAYOUT = 'SET_LAYOUT';
export const SET_LAYOUT_FULFILLED = 'SET_LAYOUT_FULFILLED';
export const SET_LAYOUT_REJECTED = 'SET_LAYOUT_REJECTED';

export const ARTICLES = 'ARTICLES';
export const ARTICLES_FULFILLED = 'ARTICLES_FULFILLED';
export const ARTICLES_REJECTED = 'ARTICLES_REJECTED';

export const READ_ARTICLE = 'READ_ARTICLE';
export const READ_ARTICLE_FULFILLED = 'READ_ARTICLE_FULFILLED';
export const READ_ARTICLE_REJECTED = 'READ_ARTICLE_REJECTED';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_FULFILLED = 'DELETE_ARTICLE_FULFILLED';
export const DELETE_ARTICLE_REJECTED = 'DELETE_ARTICLE_REJECTED';
